version: "3"
volumes:
  datavolume: {}
services:
  db:
    container_name: call-for-health-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "admin@2020"
      MYSQL_DATABASE: "call-for-health"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test@2020"
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - ./data_volume/db:/var/lib/mysql